camera:
  fov_deg: 62.2
  fps: 5
  height: 240
  width: 320
detection:
  classes:
  - 0
  - 1
  - 2
  confidence_threshold: 0.5
  iou_threshold: 0.3
  model_path: yolov8n.pt
system:
  debug_mode: true
  telemetry_interval_s: 2
ultrasonic:
  echo_pin: 24
  sample_rate_hz: 10
  trig_pin: 23
